### PR TITLE
Ensure Ninja is used by CMake

### LINKED ISSUE #6: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #6.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #6

### CODE REVIEW

**Comment by jakirkham** [comment]
cc @anthonyhtyao

**Comment by jakirkham** [comment]
On Windows, we can see a line that says

```
  -- Building for: Ninja
```

Not seeing this line on other platforms.

However we know on Linux `make` isn't installed. So we would see an error there if Linux were not using Ninja (so it must be using Ninja).

While macOS does have `make`, would expect it is doing the same thing that Linux builds are (and using Ninja).

We could probably increase the verbosity if we wanted better confirmation.

**Comment by anthonyhtyao** [comment]
Hi @jakirkham. Thanks a lot for the help. I'll look into the detail.

**Comment by jakirkham** [comment]
Ofc :)

Tried to explain the context in the commits

Think the main thing to know is that the `vc` package configures CMake to build with [a Visual Studio generator]( https://github.com/conda-forge/vc-feedstock/blob/8a739ca3ce6ff3fe8e63403687bce243a0991c5b/recipe/activate.bat#L123-L124 ), but that gets in the way of building with Ninja here. So we unset those environment variables

Otherwise this is just configuring Ninja to be used in the builds

**Pull request merged**
